### ISSUE TITLE
Testing / Feedback

### ISSUE THREAD

**Issue by mittal-parth** [WebClub-NITK/incident-2023#32]
- [x] Remove spike event 
- [x] Replace Favicon
- [x] Capitalise 'Tale' in the 'The Tale of Knights and Bards' on the Hero section
- [x] Add line breaks to FAQ section last question

Competitions
- [x] Add Unstop links (when provided)
- [x] When filters are applied to Competitions, there is a slight stutter. If that can be made smoother, it'll be nice.

**Comment by chethan-hebbar** [comment]
- [x] Change "About" text to "About Us" in About section
- [ ] Firefox browser on ubuntu is refreshing the main background at a very high rate
- [x] Last question in FAQ needs to update 27km to 17km as the distance from airport

**Comment by chethan-hebbar** [comment]
- [ ] Firefox browser on ubuntu is refreshing the main background at a very high rate

**Comment by marcdhi** [comment]
- [x] Different font sizes of the answer's in FAQ section

**Comment by ahmedfahim21** [comment]
- [x] Add `home` id to the hero section so that the **INCIDENT'23** link on navbar works
- [x] Footer not center aligned for smaller screens

![Screenshot from 2023-02-20 18-49-21](https://user-images.githubusercontent.com/99824146/220119801-336abd22-182e-450e-807c-52d0833cb157.png)

**Comment by ayush4345** [comment]
https://user-images.githubusercontent.com/99096397/220310729-e0cd5d36-ccb4-4bfb-8b85-c8d4aefd266a.mp4

When we click on faq questions then this blue color appears , if we can fix that and also add some animation on opening of accordion

**Comment by mittal-parth** [comment]
> * [x]  Add `home` id to the hero section so that the **INCIDENT'23** link on navbar works
> * [x]  Footer not center aligned for smaller screens
> 
> ![Screenshot from 2023-02-20 18-49-21](https://user-images.githubusercontent.com/99824146/220119801-336abd22-182e-450e-807c-52d0833cb157.png)

@ahmedfahim21 what should be the alignment according to you?

**Comment by ahmedfahim21** [comment]
> @ahmedfahim21 what should be the alignment according to you?

@mittal-parth 
The current alignment is also fine for a footer. Just that, I just feel the space on the right looks odd.

![image](https://user-images.githubusercontent.com/99824146/220447098-3e5dc068-838f-473c-a4e4-02dd21c35a7e.png)

I was thinking some alignment like this, but since we do not have as much content as in the image, this too might not be great.

**Comment by ayush4345** [comment]
![image](https://user-images.githubusercontent.com/99096397/220836262-89a831e4-92e2-4650-ba71-ef21613e5058.png)

competitions word is also not in centre

**Comment by mittal-parth** [comment]
> ![image](https://user-images.githubusercontent.com/99096397/220836262-89a831e4-92e2-4650-ba71-ef21613e5058.png)
> 
> competitions word is also not in centre

It's not a bug but a feature here 😂
It's supposed to be left aligned itself

**Comment by ayush4345** [comment]
> > ![image](https://user-images.githubusercontent.com/99096397/220836262-89a831e4-92e2-4650-ba71-ef21613e5058.png)
> > competitions word is also not in centre
> 
> It's not a bug but a feature here 😂 It's supposed to be left aligned itself

But don't you think it is looking sort of odd that all content is center-aligned except this?

**Comment by ayush4345** [comment]
Competitions in navbar is not working on a smaller screen, check id on the competitions component
